package MyAuthenticatorModule;


/**
* MyAuthenticatorModule/MyAuthenticator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyAuthenticatorModule.idl
* Wednesday, 10 March, 2021 1:29:57 PM IST
*/

public interface MyAuthenticator extends MyAuthenticatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MyAuthenticator
