package MyAuthenticatorModule;

/**
* MyAuthenticatorModule/MyAuthenticatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyAuthenticatorModule.idl
* Friday, 5 March, 2021 1:49:58 PM IST
*/

public final class MyAuthenticatorHolder implements org.omg.CORBA.portable.Streamable
{
  public MyAuthenticatorModule.MyAuthenticator value = null;

  public MyAuthenticatorHolder ()
  {
  }

  public MyAuthenticatorHolder (MyAuthenticatorModule.MyAuthenticator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MyAuthenticatorModule.MyAuthenticatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MyAuthenticatorModule.MyAuthenticatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MyAuthenticatorModule.MyAuthenticatorHelper.type ();
  }

}
