package MyAuthenticatorModule;


/**
* MyAuthenticatorModule/MyAuthenticatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyAuthenticatorModule.idl
* Wednesday, 10 March, 2021 1:29:57 PM IST
*/

public interface MyAuthenticatorOperations 
{
  String chech_credentials (String username, String password);
} // interface MyAuthenticatorOperations
