package MyAuthenticatorModule;


/**
* MyAuthenticatorModule/MyAuthenticator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyAuthenticatorModule.idl
* Tuesday, 9 March, 2021 6:17:54 PM IST
*/

public interface MyAuthenticator extends MyAuthenticatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MyAuthenticator
