package MyAuthenticatorModule;


/**
* MyAuthenticatorModule/MyAuthenticatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyAuthenticatorModule.idl
* Tuesday, 9 March, 2021 6:17:54 PM IST
*/

public interface MyAuthenticatorOperations 
{
  String chech_credentials (String username, String password);
} // interface MyAuthenticatorOperations
