package HelloModule;


/**
* HelloModule/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloModule.idl
* Thursday, 4 March, 2021 8:39:39 PM IST
*/

public interface HelloOperations 
{
  String print_hello (String s);
} // interface HelloOperations
